### ISSUE TITLE
February Data replacing January Data

### ISSUE THREAD

**Issue by a-m-on** [mountainMath/canpumf#3] opened 2022-03-25 19:59 UTC
Hi, 
I was starting to work with the 2022 LFS data I had downloaded with the canpumf package and noticed that the January, 2022 LFS data was identical to the February  2022 data.  Basically it was downloading the February data for both January and February.
  
When I used the code: 
<download_lfs_pumf( version = "2022-01",  destination_dir = here("Data"))>
  
I ended up with the following in the downloaded folder:  
<Data\lfs_2022-01-CSV\pub0222.csv>

I repeated the download independently and had the same result.  Is this perhaps an issue with dates in the package?

Thanks for looking into this!

**Comment by mountainMath** [comment] 2022-03-26 01:31
Thanks for flagging (again), I can reproduce the error. It downloaded the wrong version. I updated the package, should be fixed now. I also [added a vignette with a basic example of using the LFS PUMF](https://mountainmath.github.io/canpumf/articles/LFS.html). Please let me know if this fixes the issue.

**Comment by a-m-on** [comment] 2022-04-21 03:38
Hi - thank you for fixing this issue!  I ran it again and the issue was fixed.  When I download and work with the data, I noticed that December, November, and October show as names instead of numbers:

> lfs_2021_2022_ytd %>% 
+ count(survey_year, survey_month)
# A tibble: 15 x 3
   survey_year survey_month     n
   <chr>       <chr>        <int>
 1 2021        01           22366
 2 2021        02           22793
 3 2021        03           22942
 4 2021        04           23634
 5 2021        05           23956
 6 2021        06           24028
 7 2021        07           23855
 8 2021        08           23803
 9 2021        09           23962
10 2021        December     27329
11 2021        November     25717
12 2021        October      24253
13 2022        01           29696
14 2022        02           32030
15 2022        03           33986


Thanks! (  I should add that my team appreciates this package as a simpler way to approach LFS downloads for complex analysis compared to the zip files or RTRA portal - thank you for your work developing this package!)

**Comment by mountainMath** [comment] 2022-04-21 22:15
Hmm. Looks like that's due to inconsistent coding in the StatCan LFS PUMF data file vs codebook. In the data file months are zero-padded characters, in the code book they are not. So when recoding, only double-digit months will get properly recoded.

Given how important the LFS is it's probably best if I add a manual fix for this. Will also flag this for StatCan, would be nice if they could fix that on their end.

**Comment by mountainMath** [comment] 2022-04-21 22:42
Ok, I fixed it by manually adding zero-coding to month numbers in the code file. If you re-download it now it should have the months labelled consistently when you ask it to label the data.

**Closed as completed by mountainMath** 2022-04-21 22:42 UTC

**Comment by a-m-on** [comment] 2022-04-22 13:14
Fabulous - Thank you!

**Comment by a-m-on** [comment] 2022-04-22 13:15
Fabulous - thank you!
